name: First Workflow
on: push
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Test job welcome message
        run: echo "Hello, world! and Executing the test job"

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Read README.md file
        run: cat README.md
